name: LeadFinder AI

on:
  workflow_dispatch:

jobs:
  leadfinder:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - zone: western
            url: https://download.geofabrik.de/asia/india/western-zone-latest.osm.pbf

          - zone: eastern
            url: https://download.geofabrik.de/asia/india/eastern-zone-latest.osm.pbf

          - zone: northern
            url: https://download.geofabrik.de/asia/india/northern-zone-latest.osm.pbf

          - zone: southern
            url: https://download.geofabrik.de/asia/india/southern-zone-latest.osm.pbf

    steps:

      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install osmium

      - name: 🌍 Download ${{ matrix.zone }}
        run: |
          wget -O ${{ matrix.zone }}.osm.pbf ${{ matrix.url }}

      - name: 📂 Verify
        run: |
          ls -lh ${{ matrix.zone }}.osm.pbf
          file ${{ matrix.zone }}.osm.pbf

      - name: 🚀 Run Parser
        env:
          PBF_FILE: ${{ matrix.zone }}.osm.pbf
        run: |
          python app.py
